# Generated by Django 3.0.6 on 2020-10-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IfBoxHp', '0027_admininformation_uselogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('primkey', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('loginid', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('addday', models.CharField(max_length=1000)),
                ('addshift', models.CharField(max_length=1000)),
                ('access', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AdminInformation',
        ),
        migrations.DeleteModel(
            name='Diaries',
        ),
        migrations.RemoveField(
            model_name='genbainfo',
            name='compofgenba',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.RemoveField(
            model_name='runninginfo',
            name='employeeofrun',
        ),
        migrations.RemoveField(
            model_name='runninginfo',
            name='genbainfo',
        ),
        migrations.RemoveField(
            model_name='userfriends',
            name='friendid',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='friendid',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='userid',
        ),
        migrations.DeleteModel(
            name='CustomerInfo',
        ),
        migrations.DeleteModel(
            name='EmployeeInfo',
        ),
        migrations.DeleteModel(
            name='GenbaInfo',
        ),
        migrations.DeleteModel(
            name='RunningInfo',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='userfriends',
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
